### ISSUE TITLE
Script Crashes for my current save file

### ISSUE THREAD

**Issue by alainbryden** [superbob/clicker-heroes-1.0-hsoptimizer#17] opened 2016-10-14 13:03 UTC
Something about my current save file is causing the script to "stop responding" in latest firefox.

```
[data deleted]
```

**Comment by superbob** [comment] 2016-10-30 09:42
~~I can't import your save data. I seem to be truncated.~~

~~Could you save it to a text file and upload it somewhere (dropbox)?~~~

EDIT: Forget this, I've found how to have complete working savedata 👍 

Thanks in advance.

PS: I'm also deleting it from your issue request as it can contain sensitive data.

**Comment by alainbryden** [comment] 2016-10-30 15:11
Thanks, it actually just occurred to me that this probably just has to do with the 5 new heroes added. I'm pretty sure in all cases where it crashed, I had bought the first new hero - so I was a bit quick to file a bug report. More of an update request :)

**Comment by superbob** [comment] 2016-10-31 07:57
It's strange because the optimizer shouldn't take heroes (old or new) into account, only ancients and outsiders. As for me it's a bug :) I have to fix

**Comment by superbob** [comment] 2016-11-03 10:43
It's under investigation and it seems that computation takes too long because you have high levels of ancients and HS, I have to optimize the optimizer to make it faster 😄

**Comment by superbob** [comment] 2016-11-04 09:11
I've understood the root cause of this issue. It will take some time to fix this...

**Comment by alainbryden** [comment] 2016-11-04 11:57
Sorry to hear that bud. If you want to post some technical details I might be able to chip in some thoughts or code.

**Comment by CuAnnan** [comment] 2016-11-07 21:16
I expect you're going to have to replace all native number calls with references to BigInt.js (or some equivalent). Let me know if you need a hand with that.

**Comment by superbob** [comment] 2016-11-08 06:59
To be honest, I don't have time right know to work on this. Anyway, let me share some details with you :

At some point, numbers in JS are imprecise. It means that when you do

```
var bigNumber = 140000000000000000;
var bigNumberPlus10 = 140000000000000000+10;
```

You'd expect bigNumberPlus10 to equal 140000000000000010, but it will equal 140000000000000020 (you can try in chrome developer console).

And that totally breaks my algorithm in [hsoptimizer.service.js (lines 106-122)](https://github.com/superbob/clicker-heroes-1.0-hsoptimizer/blob/2baf82aee212eca1abede5748ea074ed4b192142/src/app/components/hsoptimizer/hsoptimizer.service.js#L106-L122)

The code is a little ... complicate, it could be made simpler with a dichotomy approach. Not sure it would be better though.

At this point there are 4 options :
1. Do a quick and dirty fix to 'handle' this imprecision and it will work, but be less and less precise
2. Switch with a classical dichotomy algorithm but it'll still be imprecise at some point
3. As @CuAnnan suggested, switch to BigInt.js or another library to handle big numbers and keep current logic
4. Use BigInt.js + switch to dichotomy

I have not made my decision, I'm open to suggestions and discussion.

If you want to try something with the current code, you can fork it and we can discuss with pull request.

**Comment by alainbryden** [comment] 2016-11-08 15:18
Thanks for the description of your investigation - it gave me what I needed to propose a fix. Hope you like it :)

**Comment by superbob** [comment] 2016-11-08 20:34
I'm closing the issue, thanks again for the PR.

**Closed as completed by superbob** 2016-11-08 20:34 UTC
Labels: bug
